"""A deterministic, offline model provider — the default, and load-bearing.

Most projects treat a mock model as scaffolding for unit tests. In Aleph it is a
first-class component with three jobs that matter to the product itself:

1. **The whole pipeline must run with no credentials.** A tool that audits
   public-policy evidence should be reproducible by anyone who clones it,
   including a reviewer who does not have — and should not need — an inference
   budget in order to check what the code does.
2. **CI must be able to fail.** Tests that depend on a hosted model are tests
   whose failures are ambiguous. Every check in this repository runs against
   this provider, so a red build means Aleph changed, not that a vendor did.
3. **Determinism is an epistemic property, not a convenience.** Two analyses of
   the same document must be diffable. When they differ, the difference has to
   be attributable to the document or to Aleph, never to sampling noise, and
   this provider makes that guarantee absolute for every offline run.

There is no randomness anywhere in this module — not seeded ``random``, not
``uuid``, not wall-clock time. Every value is derived by hashing the request, so
the same :class:`~aleph.llm.base.LLMRequest` produces byte-identical output on
any machine, in any process, in any order.

The core of it is a **schema-driven synthesiser**: given the JSON Schema a caller
asked for, it constructs a value that validates against it — honouring ``$ref``,
``$defs``, ``enum``, ``const``, ``required``, ``additionalProperties: false``,
numeric bounds, array cardinality, string length, ``format`` and ``pattern``.
That is what makes it useful beyond a fixture: any downstream module can pass
its real schema and get back a real, valid object, so the module can be built
and exercised end to end before a single token is ever generated by a real model.

What this provider does **not** do is judge anything. Its output is structurally
valid and semantically arbitrary. A bundle produced with it is demonstration
data and must carry ``data_status: "synthetic"``, which is exactly why that field
is required by the contract rather than optional.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable, Mapping, Sequence
from typing import Any, Final

from aleph.core.errors import ProviderError
from aleph.core.ids import stable_hash
from aleph.llm.base import (
    DEFAULT_MAX_TOKENS,
    DEFAULT_TIMEOUT_SECONDS,
    FinishReason,
    LLMProvider,
    LLMRequest,
    LLMResponse,
    RetryPolicy,
    StructuredOutputMode,
    TokenUsage,
)

__all__ = [
    "EMBEDDING_DIMENSIONS",
    "MOCK_MODEL_ID",
    "MockProvider",
    "bundle_schema",
    "synthesise_from_schema",
]

#: Recorded in every bundle's methodology block. Versioned so a change in what
#: the mock produces invalidates cached fixtures rather than silently altering
#: them.
MOCK_MODEL_ID: Final[str] = "aleph-mock/1.0.0"

#: Width of the deterministic hashed embedding. Small enough to be cheap, wide
#: enough that unrelated texts are near-orthogonal in practice.
EMBEDDING_DIMENSIONS: Final[int] = 256

#: How deep the synthesiser will follow ``$ref`` before emitting a minimal
#: value. Recursive schemas (a graph node referencing a graph node) would
#: otherwise not terminate.
_MAX_DEPTH: Final[int] = 6

_ANCHOR_DATE: Final[str] = "2026-01-15"
_ANCHOR_TIMESTAMP: Final[str] = "2026-01-15T09:00:00Z"

#: Deterministic, jurisdiction-free filler prose keyed by the field name a
#: schema used. Nothing here names a country, an institution or a person: the
#: mock must never be the place a jurisdiction detail sneaks into library code.
_FIELD_PHRASES: Final[dict[str, tuple[str, ...]]] = {
    "statement": (
        "the referenced passage states a figure without giving its basis",
        "the cited source reports a value for the period in question",
        "the document sets out a threshold and the date it takes effect",
    ),
    "reasoning": (
        "the supplied evidence addresses the quantity asserted and covers the "
        "stated period, so the assertion can be checked against it directly",
        "the evidence describes a projection rather than an outcome, so the "
        "assertion is conditional on the assumptions the projection makes",
        "no supplied item speaks to the quantity asserted, so the assertion "
        "cannot be resolved either way from this evidence set",
    ),
    "question": (
        "what value does the source record for the stated period",
        "does the document contain the provision described",
        "what does the cited projection assume",
    ),
    "summary": (
        "the assembled items agree on the figure and disagree on its basis",
        "one item bears directly on the question and the rest are contextual",
        "coverage is thin and rests on a single independent observation",
    ),
    "note": (
        "recorded for inspection; carries no weight in the verdict",
        "applies to this item only and does not generalise",
        "derived from the passage quoted above",
    ),
    "why": (
        "the item's method and scope cover the quantity being asked about",
        "the item establishes what was published, not whether it holds",
    ),
    "label": (
        "quantitative coverage of the asserted figure",
        "independent corroboration of the reported value",
        "temporal fit between the claim and the evidence",
    ),
    "text": (
        "the stated allocation applies from the beginning of the next period",
        "the measure takes effect once the stated conditions are met",
    ),
    "title": (
        "reference material for the period under review",
        "technical note accompanying the measure",
    ),
}

_GENERIC_PHRASES: Final[tuple[str, ...]] = (
    "deterministic placeholder produced offline for structural testing",
    "generated without a live model; content is arbitrary and structure is not",
    "offline synthesis: shape follows the schema, meaning follows nothing",
)


# ---------------------------------------------------------------------------
# Deterministic value stream
# ---------------------------------------------------------------------------


class _Stream:
    """A counter-driven hash stream. Reproducible, stateless across processes.

    Not a PRNG: every draw is ``hash(seed, counter)``, so two runs with the same
    seed produce the same sequence regardless of platform, Python build or the
    order other components happened to draw in.
    """

    __slots__ = ("_seed", "_counter")

    def __init__(self, *seed_parts: object) -> None:
        self._seed = stable_hash(*seed_parts, length=32)
        self._counter = 0

    def _draw(self) -> int:
        self._counter += 1
        return int(stable_hash(self._seed, self._counter, length=16), 16)

    def below(self, n: int) -> int:
        """A value in ``[0, n)``."""
        return self._draw() % max(1, n)

    def unit(self) -> float:
        """A value in ``[0, 1)``, rounded to 6 places so it serialises cleanly."""
        return round((self._draw() % 1_000_000) / 1_000_000, 6)

    def choice(self, items: Sequence[Any]) -> Any:
        if not items:
            raise ValueError("cannot choose from an empty sequence")
        return items[self.below(len(items))]

    def between(self, low: float, high: float) -> float:
        if high <= low:
            return low
        return round(low + (high - low) * self.unit(), 6)

    def int_between(self, low: int, high: int) -> int:
        if high <= low:
            return low
        return low + self.below(high - low + 1)


# ---------------------------------------------------------------------------
# Schema-driven synthesis
# ---------------------------------------------------------------------------


def synthesise_from_schema(
    schema: Mapping[str, Any],
    *,
    seed: object = "aleph",
    root: Mapping[str, Any] | None = None,
    documents: Mapping[str, Mapping[str, Any]] | None = None,
) -> Any:
    """Construct a value that validates against ``schema``.

    Deterministic in ``seed``: the same schema and seed always produce the same
    value. Supports the subset of JSON Schema draft 2020-12 that Aleph's own
    contract uses, which is deliberately a subset — a synthesiser that guessed
    at exotic keywords would produce values that *look* valid and are not.

    Args:
        schema: The schema to satisfy.
        seed: Anything hashable-to-string; distinct seeds give distinct values.
        root: The document ``$ref`` pointers resolve against. Defaults to
            ``schema`` itself, which is the usual case.
        documents: Sibling schema documents keyed by the filename a ``$ref``
            uses, e.g. ``{"common.json": {...}}``. Aleph's own contract is split
            across files that cross-reference each other by relative name, so
            without this the shared ``$defs`` — every confidence, every id,
            every enum — would not resolve. An unresolvable ``$ref`` degrades to
            an unconstrained value rather than raising, because a caller may
            legitimately supply only the fragment they care about.

    Returns:
        A JSON-safe Python value.

    Raises:
        ProviderError: A ``pattern`` constraint could not be satisfied. Failing
            loudly is correct: emitting a string that violates the pattern would
            push an invalid value into a bundle under the appearance of success.
    """
    stream = _Stream("synthesise", seed)
    base = dict(root if root is not None else schema)
    if documents:
        base = bundle_schema(base, documents)
        if root is None:
            schema = base
    refs = _Refs(base, documents)
    return _synth(dict(schema), refs, stream, "", 0)


def bundle_schema(
    schema: Mapping[str, Any], documents: Mapping[str, Mapping[str, Any]]
) -> dict[str, Any]:
    """Inline cross-file ``$ref`` targets into one self-contained document.

    Aleph's contract is split across files that reference each other by relative
    name (``common.json#/$defs/confidence``), and a target pulled in that way
    carries *its own* internal references, which resolve against *its* file, not
    against the file that imported it. Resolving those lazily would need a
    resolution scope threaded through every recursive call; inlining once up
    front is simpler and has the same result.

    Each imported target lands in the root's ``$defs`` under a mangled name that
    records where it came from, so a bundled schema stays readable when a
    synthesis failure has to be diagnosed.
    """
    bundled = _deepcopy(schema)
    defs: dict[str, Any] = dict(bundled.get("$defs") or {})
    bundled["$defs"] = defs

    imported: dict[tuple[str, str], str] = {}
    queue: list[tuple[str, str]] = []

    def mangle(document_name: str, pointer: str) -> str:
        slug = re.sub(r"[^A-Za-z0-9]+", "_", document_name).strip("_")
        tail = re.sub(r"[^A-Za-z0-9]+", "_", pointer).strip("_")
        return f"{slug}__{tail}" if tail else slug

    def rewrite(node: Any, current_document: str | None) -> Any:
        """Rewrite every ``$ref`` in ``node`` to a root-local pointer."""
        if isinstance(node, list):
            return [rewrite(item, current_document) for item in node]
        if not isinstance(node, dict):
            return node
        out: dict[str, Any] = {}
        for key, value in node.items():
            if key == "$ref" and isinstance(value, str):
                document_name, _, pointer = value.partition("#")
                target_document = document_name or current_document
                if not target_document:
                    out[key] = value  # already root-local
                    continue
                target_document = target_document.rsplit("/", 1)[-1]
                pointer = pointer or "/"
                name = imported.get((target_document, pointer))
                if name is None:
                    name = mangle(target_document, pointer)
                    imported[(target_document, pointer)] = name
                    queue.append((target_document, pointer))
                out[key] = f"#/$defs/{name}"
            else:
                out[key] = rewrite(value, current_document)
        return out

    bundled = rewrite(bundled, None)
    defs = bundled.setdefault("$defs", {})

    guard = 0
    while queue and guard < 2000:
        guard += 1
        document_name, pointer = queue.pop(0)
        name = imported[(document_name, pointer)]
        if name in defs:
            continue
        document = documents.get(document_name)
        target = _pointer_into(document, pointer) if document is not None else None
        # A ref Aleph cannot resolve becomes an unconstrained schema rather than
        # an error: a caller may legitimately hand over only a fragment.
        defs[name] = rewrite(_deepcopy(target), document_name) if target is not None else {}
    return bundled


def _deepcopy(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {key: _deepcopy(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_deepcopy(item) for item in value]
    return value


def _pointer_into(document: Mapping[str, Any], pointer: str) -> Mapping[str, Any] | None:
    node: Any = document
    for part in pointer.strip("/").split("/"):
        if not part:
            continue
        key = part.replace("~1", "/").replace("~0", "~")
        if not isinstance(node, Mapping) or key not in node:
            return None
        node = node[key]
    return node if isinstance(node, Mapping) else None


class _Refs:
    """Resolves ``$ref`` against the root document and its named siblings."""

    __slots__ = ("root", "documents")

    def __init__(
        self,
        root: Mapping[str, Any],
        documents: Mapping[str, Mapping[str, Any]] | None = None,
    ) -> None:
        self.root = root
        self.documents = dict(documents or {})

    def resolve(self, schema: Mapping[str, Any]) -> dict[str, Any]:
        """Follow ``$ref`` chains, merging any sibling keywords over the target."""
        seen = 0
        current = dict(schema)
        while "$ref" in current and seen < _MAX_DEPTH:
            ref = str(current.pop("$ref"))
            seen += 1
            target = self._lookup(ref)
            if target is None:
                break
            current = _merge(dict(target), current)
        return current

    def _lookup(self, ref: str) -> Mapping[str, Any] | None:
        document_name, _, pointer = ref.partition("#")
        if document_name:
            document = self.documents.get(document_name)
            if document is None:
                # Also accept a bare basename, so "./common.json" and
                # "common.json" behave the same.
                document = self.documents.get(document_name.rsplit("/", 1)[-1])
            if document is None:
                return None
        else:
            document = self.root
        node: Any = document
        for part in pointer.strip("/").split("/"):
            if not part:
                continue
            key = part.replace("~1", "/").replace("~0", "~")
            if not isinstance(node, Mapping) or key not in node:
                return None
            node = node[key]
        return node if isinstance(node, Mapping) else None


def _synth(
    schema: Mapping[str, Any],
    refs: _Refs,
    stream: _Stream,
    field_name: str,
    depth: int,
) -> Any:
    schema = refs.resolve(schema)

    if "const" in schema:
        return schema["const"]
    if "default" in schema and depth > 0:
        return schema["default"]
    enum = schema.get("enum")
    if enum:
        return stream.choice(list(enum))

    if "allOf" in schema:
        merged: dict[str, Any] = {}
        for part in schema["allOf"]:
            merged = _merge(merged, refs.resolve(part))
        merged = _merge(merged, {k: v for k, v in schema.items() if k != "allOf"})
        return _synth(merged, refs, stream, field_name, depth)

    for combinator in ("oneOf", "anyOf"):
        options = schema.get(combinator)
        if options:
            branch = _pick_branch(options, refs, stream, depth)
            return _synth(branch, refs, stream, field_name, depth)

    declared = schema.get("type")
    types = [declared] if isinstance(declared, str) else list(declared or [])
    if not types:
        types = ["object" if "properties" in schema else "string"]

    # A nullable field at the depth limit becomes null; that is how a recursive
    # schema terminates without inventing another level of structure.
    if depth >= _MAX_DEPTH and "null" in types:
        return None
    chosen = next((t for t in types if t != "null"), "null")

    if chosen == "object":
        return _synth_object(schema, refs, stream, depth)
    if chosen == "array":
        return _synth_array(schema, refs, stream, field_name, depth)
    if chosen == "string":
        return _synth_string(schema, stream, field_name)
    if chosen == "integer":
        return _synth_integer(schema, stream)
    if chosen == "number":
        return _synth_number(schema, stream)
    if chosen == "boolean":
        return stream.below(2) == 1
    return None


def _pick_branch(
    options: Sequence[Mapping[str, Any]],
    refs: _Refs,
    stream: _Stream,
    depth: int,
) -> Mapping[str, Any]:
    """Choose a branch of ``oneOf``/``anyOf``.

    Non-null branches are preferred until the depth limit, where null is
    preferred: that is what stops a self-referential schema from recursing while
    still producing a populated value at shallow depths.
    """
    resolved = [refs.resolve(opt) for opt in options]
    nulls = [opt for opt in resolved if opt.get("type") == "null"]
    others = [opt for opt in resolved if opt.get("type") != "null"]
    if depth >= _MAX_DEPTH and nulls:
        return nulls[0]
    if others:
        return others[stream.below(len(others))]
    return resolved[0]


def _synth_object(
    schema: Mapping[str, Any], refs: _Refs, stream: _Stream, depth: int
) -> dict[str, Any]:
    properties: Mapping[str, Any] = schema.get("properties") or {}
    required = list(schema.get("required") or [])
    out: dict[str, Any] = {}

    # Required properties always; optional ones deterministically about half the
    # time, so a mock run exercises both the present and absent branches of
    # downstream code rather than only the fullest possible object.
    for name, sub in properties.items():
        include = name in required or stream.below(2) == 1 or depth == 0
        if not include:
            continue
        out[name] = _synth(sub, refs, stream, name, depth + 1)

    for name in required:
        if name not in out:
            sub = properties.get(name, {"type": "string"})
            out[name] = _synth(sub, refs, stream, name, depth + 1)

    min_props = int(schema.get("minProperties", 0) or 0)
    additional = schema.get("additionalProperties", True)
    if len(out) < min_props and additional is not False:
        sub_schema = additional if isinstance(additional, Mapping) else {"type": "string"}
        while len(out) < min_props:
            key = f"key_{len(out)}"
            out[key] = _synth(sub_schema, refs, stream, key, depth + 1)
    return out


def _synth_array(
    schema: Mapping[str, Any],
    refs: _Refs,
    stream: _Stream,
    field_name: str,
    depth: int,
) -> list[Any]:
    items = schema.get("items")
    min_items = int(schema.get("minItems", 0) or 0)
    max_items_raw = schema.get("maxItems")
    max_items = int(max_items_raw) if max_items_raw is not None else None

    if items is None:
        return []
    count = max(min_items, 1)
    if depth >= _MAX_DEPTH:
        count = min_items
    if max_items is not None:
        count = min(count, max_items)
    return [_synth(items, refs, stream, field_name, depth + 1) for _ in range(count)]


def _synth_integer(schema: Mapping[str, Any], stream: _Stream) -> int:
    low = schema.get("minimum")
    high = schema.get("maximum")
    if low is None and schema.get("exclusiveMinimum") is not None:
        low = float(schema["exclusiveMinimum"]) + 1
    if high is None and schema.get("exclusiveMaximum") is not None:
        high = float(schema["exclusiveMaximum"]) - 1
    lo = int(low) if low is not None else 0
    hi = int(high) if high is not None else lo + 10
    if hi < lo:
        hi = lo
    return stream.int_between(lo, hi)


def _synth_number(schema: Mapping[str, Any], stream: _Stream) -> float:
    low = schema.get("minimum", schema.get("exclusiveMinimum", 0.0))
    high = schema.get("maximum", schema.get("exclusiveMaximum", None))
    lo = float(low if low is not None else 0.0)
    hi = float(high if high is not None else lo + 100.0)
    if hi < lo:
        hi = lo
    return stream.between(lo, hi)


def _synth_string(schema: Mapping[str, Any], stream: _Stream, field_name: str) -> str:
    pattern = schema.get("pattern")
    fmt = schema.get("format")
    min_length = int(schema.get("minLength", 0) or 0)
    max_length_raw = schema.get("maxLength")
    max_length = int(max_length_raw) if max_length_raw is not None else None

    if pattern:
        value = _string_for_pattern(str(pattern), stream, min_length)
        return value

    if fmt:
        value = _string_for_format(str(fmt), stream)
        if value is not None:
            return value

    body = _phrase_for(field_name, stream)
    while len(body) < min_length:
        body = f"{body}; {_phrase_for(field_name, stream)}"
    if max_length is not None and len(body) > max_length:
        body = body[:max_length].rstrip()
    return body


def _string_for_format(fmt: str, stream: _Stream) -> str | None:
    if fmt == "date-time":
        return _ANCHOR_TIMESTAMP
    if fmt == "date":
        return _ANCHOR_DATE
    if fmt == "uri" or fmt == "uri-reference":
        return f"https://example.invalid/aleph/mock/{stream.below(9999)}"
    if fmt == "email":
        return "mock@example.invalid"
    if fmt == "duration":
        return "P1D"
    return None


def _phrase_for(field_name: str, stream: _Stream) -> str:
    options = _FIELD_PHRASES.get(field_name)
    if not options:
        for key, phrases in _FIELD_PHRASES.items():
            if phrases and key and key in field_name:
                options = phrases
                break
    return str(stream.choice(list(options or _GENERIC_PHRASES)))


# -- pattern satisfaction ---------------------------------------------------

#: Values tried first for a ``pattern`` constraint. Covering the shapes Aleph's
#: own contract uses means the common case never reaches the generic generator.
_PATTERN_CANDIDATES: Final[tuple[str, ...]] = (
    "clm:1",
    "ev:1",
    "doc:mock-document",
    "prov:mock-document:1",
    "prop:mock-document:1",
    "art:mock-outlet:1",
    "cluster:1",
    "contra:1",
    "actor:mock-actor",
    "node:mock-node",
    "edge:mock-edge",
    "src:mock-source",
    "axis:central_vs_local",
    "job:mock",
    _ANCHOR_TIMESTAMP,
    _ANCHOR_DATE,
    "1.0.0",
    "CLP",
    "USD",
    "mock-document",
    "mock_value",
    "mock",
    "0123456789abcdef0123456789abcdef",
    "es",
    "es-CL",
)

_CLASS_SAMPLE: Final[dict[str, str]] = {
    r"\d": "1",
    r"\w": "a",
    r"\s": " ",
    r"\.": ".",
    r"\-": "-",
    r"\/": "/",
    r"\:": ":",
}


def _string_for_pattern(pattern: str, stream: _Stream, min_length: int) -> str:
    """Return a string matching ``pattern``, or raise.

    Tries a table of known-good values first, then a small constructive
    generator for the anchored ``literal + character-class`` shapes the contract
    uses. Every candidate is verified with :func:`re.fullmatch` before it is
    returned, so this function cannot emit a value that violates the constraint.
    """
    compiled = re.compile(pattern)

    ordered = list(_PATTERN_CANDIDATES)
    # Rotate deterministically so repeated fields in one object do not all
    # collapse to the same id.
    offset = stream.below(len(ordered))
    ordered = ordered[offset:] + ordered[:offset]

    for candidate in ordered:
        if _matches(compiled, candidate, min_length):
            return candidate

    constructed = _construct_for_pattern(pattern)
    if constructed is not None:
        for suffix in ("", "1", "a", "-1", "01"):
            candidate = constructed + suffix
            if _matches(compiled, candidate, min_length):
                return candidate

    raise ProviderError(
        "MockProvider cannot synthesise a string for this pattern; register an "
        "explicit canned response for this call",
        provider="mock",
        operation="synthesise",
        retryable=False,
        pattern=pattern,
    )


def _matches(compiled: re.Pattern[str], candidate: str, min_length: int) -> bool:
    if len(candidate) < min_length:
        return False
    anchored = compiled.pattern.startswith("^") and compiled.pattern.endswith("$")
    if anchored:
        return compiled.match(candidate) is not None
    return compiled.search(candidate) is not None


_TOKEN_RE: Final[re.Pattern[str]] = re.compile(
    r"""
    (?P<group>\((?:\?:)?[^()]*\))     # (a|b|c) or (?:a|b|c)
  | (?P<klass>\[[^\]]+\])             # [A-Za-z0-9._-]
  | (?P<escape>\\[dwWsSD.\-/:])       # \d \w \.
  | (?P<literal>[^\\\[\]()*+?{}^$|])  # a plain character
    """,
    re.VERBOSE,
)

# No leading ``^``: this is used with ``match(body, index)``, and ``^`` would
# only ever match at position zero of the whole string.
_QUANT_RE: Final[re.Pattern[str]] = re.compile(r"(?:\{(\d+)(?:,(\d*))?\}|([*+?]))")


def _construct_for_pattern(pattern: str) -> str | None:
    """Build a minimal string for the anchored subset of regex Aleph uses.

    Handles literals, character classes, simple alternation groups and the
    ``* + ? {n} {n,m}`` quantifiers. Returns ``None`` for anything richer rather
    than producing a string that only looks right.
    """
    body = pattern
    if body.startswith("^"):
        body = body[1:]
    if body.endswith("$"):
        body = body[:-1]

    out: list[str] = []
    index = 0
    length = len(body)
    while index < length:
        match = _TOKEN_RE.match(body, index)
        if match is None:
            return None
        index = match.end()
        piece = _sample_token(match)
        if piece is None:
            return None
        repeat = 1
        quant = _QUANT_RE.match(body, index)
        if quant is not None:
            index = quant.end()
            if quant.group(3) == "*" or quant.group(3) == "?":
                repeat = 0 if quant.group(3) == "*" else 1
            elif quant.group(3) == "+":
                repeat = 1
            else:
                repeat = int(quant.group(1))
        out.append(piece * repeat)
    return "".join(out)


def _sample_token(match: re.Match[str]) -> str | None:
    if match.group("literal") is not None:
        return match.group("literal")
    if match.group("escape") is not None:
        return _CLASS_SAMPLE.get(match.group("escape"), "a")
    if match.group("klass") is not None:
        return _sample_class(match.group("klass"))
    group = match.group("group")
    if group is not None:
        inner = group[1:-1]
        if inner.startswith("?:"):
            inner = inner[2:]
        first = inner.split("|")[0]
        return first if first and re.fullmatch(r"[A-Za-z0-9_.\-]+", first) else None
    return None


def _sample_class(klass: str) -> str | None:
    inner = klass[1:-1]
    if inner.startswith("^"):
        return "a"
    ranges = re.findall(r"([A-Za-z0-9])-([A-Za-z0-9])", inner)
    if ranges:
        low, _high = ranges[0]
        return low
    literals = re.sub(r"\\(.)", r"\1", inner)
    return literals[0] if literals else None


def _merge(base: Mapping[str, Any], overlay: Mapping[str, Any]) -> dict[str, Any]:
    out = dict(base)
    for key, value in overlay.items():
        if key == "required":
            out[key] = sorted({*(out.get("required") or []), *value})
        elif key == "properties":
            merged = dict(out.get("properties") or {})
            merged.update(value)
            out[key] = merged
        else:
            out[key] = value
    return out


# ---------------------------------------------------------------------------
# The provider
# ---------------------------------------------------------------------------


class MockProvider(LLMProvider):
    """A model that answers from a hash of the question.

    Args:
        model: Identifier recorded in responses and in a bundle's methodology.
        seed: Mixed into every derivation, so two mock providers configured
            differently give different — but each internally reproducible —
            answers.
        canned: Exact responses keyed by ``purpose`` or by a substring of the
            prompt. A value may be a JSON-safe object, a string, or a callable
            taking the request. Consulted before synthesis, which is how a test
            pins a specific answer without giving up determinism everywhere else.
        record_calls: Keep every request for later assertion. On by default: the
            call log is how a test checks that the blind evaluator was handed a
            redacted context and nothing more.
    """

    name = "mock"

    def __init__(
        self,
        *,
        model: str = MOCK_MODEL_ID,
        seed: int | str = 20260807,
        temperature: float = 0.0,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
        canned: Mapping[str, Any] | None = None,
        record_calls: bool = True,
    ) -> None:
        super().__init__(
            model=model,
            temperature=temperature,
            max_tokens=max_tokens,
            timeout=timeout,
            # One attempt: a deterministic provider that failed validation once
            # would fail it identically forever, so retrying is pure latency.
            retry=RetryPolicy(max_attempts=1),
            sleep=lambda _seconds: None,
        )
        self.seed = seed
        self._canned: dict[str, Any] = dict(canned or {})
        self.record_calls = record_calls
        self.calls: list[LLMRequest] = []

    # -- configuration ------------------------------------------------------

    @classmethod
    def from_config(cls, config: Any = None, **overrides: Any) -> MockProvider:
        from aleph.core.config import get_config

        cfg = config or get_config()
        kwargs: dict[str, Any] = {
            "seed": cfg.seed,
            "temperature": cfg.llm_temperature,
        }
        kwargs.update(overrides)
        return cls(**kwargs)

    def register(self, key: str, payload: Any | Callable[[LLMRequest], Any]) -> None:
        """Pin the answer for calls whose ``purpose`` or prompt matches ``key``."""
        self._canned[key] = payload

    def clear_calls(self) -> None:
        self.calls.clear()

    @property
    def call_count(self) -> int:
        return len(self.calls)

    @property
    def is_deterministic(self) -> bool:
        """True, and it is the reason this provider exists."""
        return True

    # -- invocation ---------------------------------------------------------

    def _invoke(self, request: LLMRequest) -> LLMResponse:
        if self.record_calls:
            self.calls.append(request)
        return self._respond(request)

    async def _ainvoke(self, request: LLMRequest) -> LLMResponse:
        """Identical to :meth:`_invoke`; no I/O, so nothing to await.

        Deliberately not routed through a thread: an async caller must get the
        same answer as a sync one, and adding concurrency here would add a way
        for them to differ.
        """
        if self.record_calls:
            self.calls.append(request)
        return self._respond(request)

    def _respond(self, request: LLMRequest) -> LLMResponse:
        fingerprint = request.fingerprint()
        payload = self._canned_for(request)

        if payload is None and request.schema is not None:
            payload = synthesise_from_schema(request.schema, seed=(self.seed, fingerprint))

        if payload is None:
            text = self._prose(request, fingerprint)
        elif isinstance(payload, str):
            text = payload
        else:
            text = json.dumps(payload, ensure_ascii=False, indent=2)

        mode = (
            StructuredOutputMode.JSON_SCHEMA
            if request.schema is not None
            else StructuredOutputMode.NONE
        )
        return LLMResponse(
            text=text,
            model=self.model_id,
            provider=self.name,
            usage=TokenUsage(
                prompt_tokens=_estimate_tokens(request.prompt) + _estimate_tokens(request.system),
                completion_tokens=_estimate_tokens(text),
            ),
            # Derived from the request rather than measured, so that a bundle
            # built offline is byte-identical across runs and machines.
            latency_ms=1.0 + (int(fingerprint[:4], 16) % 500) / 100.0,
            finish_reason=FinishReason.STOP,
            structured_output_mode=mode,
        )

    def _canned_for(self, request: LLMRequest) -> Any | None:
        if not self._canned:
            return None
        candidates: list[Any] = []
        if request.purpose and request.purpose in self._canned:
            candidates.append(self._canned[request.purpose])
        for key, value in self._canned.items():
            if key and key in request.prompt:
                candidates.append(value)
        if not candidates:
            return None
        chosen = candidates[0]
        return chosen(request) if callable(chosen) else chosen

    def _prose(self, request: LLMRequest, fingerprint: str) -> str:
        """Deterministic free text for schema-less calls.

        Echoes salient terms from the prompt so a caller inspecting the output
        can tell which call produced it, and says plainly that it came from the
        offline provider — free text that silently looked like analysis would be
        the easiest way for demonstration content to be mistaken for a result.
        """
        stream = _Stream(self.seed, fingerprint)
        terms = _salient_terms(request.prompt, limit=6)
        subject = ", ".join(terms) if terms else "the supplied input"
        return (
            f"Offline deterministic response (provider={self.name}, "
            f"model={self.model_id}). Concerning {subject}: "
            f"{stream.choice(list(_GENERIC_PHRASES))}."
        )

    # -- embeddings ---------------------------------------------------------

    def embed(self, texts: Sequence[str]) -> list[list[float]]:
        """Hashed bag-of-words vectors, L2-normalised.

        A real, usable implementation rather than a stub: identical texts give
        identical vectors, texts sharing vocabulary sit closer than texts that
        do not, and no network or model is involved. Adequate for clustering and
        near-duplicate detection in an offline run. It carries no semantics
        beyond lexical overlap, and nothing in the factual path may treat it as
        if it did.
        """
        return [_hashed_embedding(text) for text in texts]


# ---------------------------------------------------------------------------
# small helpers
# ---------------------------------------------------------------------------

_WORD_RE: Final[re.Pattern[str]] = re.compile(r"[^\W\d_]{3,}", re.UNICODE)


def _estimate_tokens(text: str | None) -> int:
    """Four characters per token — the usual rough rule, stated as a rough rule."""
    if not text:
        return 0
    return max(1, len(text) // 4)


def _salient_terms(text: str, *, limit: int) -> list[str]:
    counts: dict[str, int] = {}
    for word in _WORD_RE.findall(text.lower()):
        counts[word] = counts.get(word, 0) + 1
    ranked = sorted(counts.items(), key=lambda item: (-item[1], item[0]))
    return [word for word, _ in ranked[:limit]]


def _hashed_embedding(text: str, dimensions: int = EMBEDDING_DIMENSIONS) -> list[float]:
    vector = [0.0] * dimensions
    for word in _WORD_RE.findall(text.lower()):
        digest = int(stable_hash("embed", word, length=16), 16)
        index = digest % dimensions
        sign = 1.0 if (digest >> 8) % 2 == 0 else -1.0
        vector[index] += sign
    norm = sum(value * value for value in vector) ** 0.5
    if norm == 0.0:
        return vector
    return [round(value / norm, 8) for value in vector]
